import { StyleSheet } from 'react-native';
import Responsive, { AppFont } from './responsive';
import { Theme } from '.';
import { moderateScale } from 'react-native-size-matters';

const { getWidth, getHeight, AppFonts } = Responsive;

const combineStyle = StyleSheet.create({

 rowStyle:{
  flexDirection:"row",
  alignItems:"center", 
 },
  rowStyle2:{
  flexDirection:"row",
  alignItems:"center", 
  justifyContent:"center"
 },
 text28:{
    fontSize:moderateScale(28),
    fontFamily:Theme.fontFamily.GlaxinSemiBold,
    color:Theme.colors.white,
 },
 text18Semi:{
   fontSize:moderateScale(18),
   fontFamily:Theme.fontFamily.GlaxinSemiBold,
   color:Theme.colors.white,
 },
  text18mid:{
   fontSize:moderateScale(18),
   fontFamily:Theme.fontFamily.GlaxinMedium,
   color:Theme.colors.white,
 },
  text18Bold:{
   fontSize:moderateScale(18),
   fontFamily:Theme.fontFamily.GlaxinBold,
   color:Theme.colors.white,
 },
 text24Mid:{
   fontSize:moderateScale(24),
   fontFamily:Theme.fontFamily.GlaxinMedium,
   color:Theme.colors.white,
 },
 text24Bold:{
  fontSize:moderateScale(24),
  fontFamily:Theme.fontFamily.GlaxinBold,
  color:Theme.colors.white,
},
 text24Semi:{
  fontSize:moderateScale(24),
  fontFamily:Theme.fontFamily.GlaxinSemiBold,
  color:Theme.colors.white,
 },
 text16Semi:{
  fontSize:moderateScale(16),
  fontFamily:Theme.fontFamily.GlaxinSemiBold,
  color:Theme.colors.white,
 },
 text20Semi:{
  fontSize:moderateScale(20),
  fontFamily:Theme.fontFamily.GlaxinSemiBold,
  color:Theme.colors.black,
 },
 text30Bold:{
fontSize:moderateScale(30),
fontFamily:Theme.fontFamily.GlaxinBold,
color:Theme.colors.white,
 },
  text28Bold:{
fontSize:moderateScale(28),
fontFamily:Theme.fontFamily.GlaxinBold,
color:Theme.colors.white,
 },
 text32Bold:{
  fontSize:moderateScale(32),
  fontFamily:Theme.fontFamily.GlaxinBold,
  color:Theme.colors.white,
   },
 text16Regular:{
  fontSize:moderateScale(16),
  fontFamily:Theme.fontFamily.GlaxinRegular,
  color:Theme.colors.white,
 },
 text16Mid:{
  fontSize:moderateScale(16),
  fontFamily:Theme.fontFamily.GlaxinMedium,
  color:Theme.colors.white,
 },
 text16Bold:{
  fontSize:moderateScale(16),
  fontFamily:Theme.fontFamily.GlaxinBold,
  color:Theme.colors.white,
 },
 text14Mid:{
  fontSize:moderateScale(14),
  fontFamily:Theme.fontFamily.GlaxinMedium,
  color:Theme.colors.white,
 },
 text12Regular:{
  fontSize:moderateScale(12),
  fontFamily:Theme.fontFamily.GlaxinRegular,
  color:Theme.colors.white,
 },
 text14Regular:{
  fontSize:moderateScale(14),
  fontFamily:Theme.fontFamily.GlaxinRegular,
  color:Theme.colors.white,
 },
 text12Mid:{
  fontSize:moderateScale(12),
  fontFamily:Theme.fontFamily.GlaxinMedium,
  color:Theme.colors.white,
 },
  text10Bold:{
  fontSize:moderateScale(10),
  fontFamily:Theme.fontFamily.GlaxinBold,
  color:Theme.colors.white,
 },
 text10Regular:{
  fontSize:moderateScale(10),
  fontFamily:Theme.fontFamily.GlaxinRegular,
  color:Theme.colors.white,
 },
 text12Bold:{
  fontSize:moderateScale(12),
  fontFamily:Theme.fontFamily.GlaxinBold,
  color:Theme.colors.white,
 },
 text14Bold:{
  fontSize:moderateScale(14),
  fontFamily:Theme.fontFamily.GlaxinBold,
  color:Theme.colors.white,
 },
 checkboxStyle:{
  width:moderateScale(20),
  height:moderateScale(20),
  borderWidth:1,
  borderColor:Theme.colors.lightTransparet,
  borderRadius:moderateScale(4),
  backgroundColor:Theme.colors.lightTransparet,
 }

});

export default combineStyle;
