import UnAuthStack from "./UnAuthStack";

export const Routes = {
  SplashScreen: 'SplashScreen',
  SplashScreen2: 'SplashScreen2',
  SplashScreen3: 'SplashScreen3',
  OnboardingScreen: 'OnboardingScreen',
  OnboardingScreen2: 'OnboardingScreen2',
  OnboardingScreen3: 'OnboardingScreen3',
  FirstOnboardingScreen: 'FirstOnboardingScreen',
  Onboarding20Screen: 'Onboarding20Screen',
  AuthStack:"AuthStack",
  UnAuthStack: 'UnAuthStack',
  LoginScreen:"LoginScreen",
  Signup:"Signup",
  ForgetPassword:"ForgetPassword",
  VerifyOtp:"VerifyOtp",
  ResetPassword:"ResetPassword",
  SetupProfile:"SetupProfile",
  Map:"Map",
  Meetup:"Meetup",
  Chats:"Chats",
  Profile:"Profile",
  BottomStack:"BottomStack",
  EditProfile:"EditProfile",
  EditName:"EditName",
  EditBio:"EditBio",
  UpdatePassword:"UpdatePassword",
  PrivacyPolicy:"PrivacyPolicy",
  HelpCenter:"HelpCenter",
  Language:"Language",
  MeetupDetails:"MeetupDetails",
  CreateMeetup:"CreateMeetup",
  Notification:"Notification",
  ChatScreen:"ChatScreen",
  EditSkill:"EditSkill",
  HostProfile: 'HostProfile',
};
